version: '3'

services:
  forumDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynet
  forumDBMigration:
    image: forumdbmigration
    networks:
      - mynet
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mynet
  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - mynet
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynet
  user:
    image: usermigration
    ports:
      - 5000:5000
    networks:
      - mynet
  admin:
    image: adminmigration
    ports:
      - 5001:5001
    networks:
      - mynet
  deamon:
    image: daemonmigration
    networks:
      - mynet

volumes:
  dbdata:

networks:
  mynet:
    driver: overlay